// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiucstlnchmwomgmuatw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpdWNzdGxuY2htd29tZ211YXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDMxNDUsImV4cCI6MjA2OTk3OTE0NX0.fktX7FcDz4xFj9kbToSrNiSmcS-6Eb45hL9gC86GeXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});